# Screen
TILEWIDTH = 16
TILEHEIGHT = 16
SCALE = 2
LBORDER = 2
BBORDER = 3
NROWS = (8+BBORDER+LBORDER)*SCALE
NCOLS = (16+2*LBORDER)*SCALE
SCREENWIDTH = NCOLS*TILEWIDTH
SCREENHEIGHT = NROWS*TILEHEIGHT
SCREENSIZE = (SCREENWIDTH, SCREENHEIGHT)
SCALEWIDTH = SCALE*TILEWIDTH
SCALEHEIGHT = SCALE*TILEHEIGHT

# Movement Directions
STOP = 0
UP = 1
DOWN = -1
LEFT = 2
RIGHT = -2

# Entities
PLAYER = 0
PELLET = 1
POWERP = 2
ENEMY = 3

# Colors
BLACK = (0, 0, 0)
WHITE = (255, 255, 255)
RED = (255, 0, 0)
